### ISSUE TITLE
Fix support for wsdl/schema validation

### ISSUE THREAD

**Issue by plogik** [skjolber/mockito-soap-cxf#9]
It would be nice to have schema validation with wsdl work. It currently throws exception because the proxy gets a default invalid name:
`javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Could not find definition for service {http://proxy.sun.com/}$Proxy112Service
    at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:375)
	at org.apache.cxf.jaxws.EndpointImpl.publish(EndpointImpl.java:255)
	at com.skjolberg.mockito.soap.SoapEndpointRule.proxy(SoapEndpointRule.java:282)`

Is there a workaround for fixing this, or is it on the roadmap to make it work out of the box?

Thanks

**Comment by skjolber** [comment]
@plogik I'll have to investigate. If you find a solution, please submit a PR.

**Comment by superjerico** [comment]
I have related issue.
This line works fine (construction of WS based on class):
`wsMock = soap.mock(UserAuthentication.class, "http://localhost:12345/userAuthentication");`

While as this variation:
`wsMock = soap.mock(UserAuthentication.class, "http://localhost:12345/userAuthentication", "classpath:/META-INF/wsdl/userAuthentication.wsdl");`
fails with error:
`org.apache.cxf.service.factory.ServiceConstructionException: Could not find definition for service {http://proxy.sun.com/}$Proxy76Service.

	at org.apache.cxf.wsdl11.WSDLServiceFactory.create(WSDLServiceFactory.java:157)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromWSDL(ReflectionServiceFactoryBean.java:408)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:528)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:263)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199)
	at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103)
	at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
	at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
	at org.apache.cxf.jaxws.EndpointImpl.getServer(EndpointImpl.java:460)
	at org.apache.cxf.jaxws.EndpointImpl.getServer(EndpointImpl.java:384)
	at com.skjolberg.mockito.soap.SoapEndpointRule.proxy(SoapEndpointRule.java:278)
	at com.skjolberg.mockito.soap.SoapServiceRule.mock(SoapServiceRule.java:126)
	at com.skjolberg.mockito.soap.SoapServiceRule.mock(SoapServiceRule.java:105)
	at com.db.gm.riskengine.AbstractCtxIntegrationTest.setUp(AbstractCtxIntegrationTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

I walked through debug and can confirm that issue is that org.apache.cxf.common.util.ClassHelper is unable to unwrap EasyMock Proxy class as cxf uses SpringAopClassHelper.

**Comment by skjolber** [comment]
XSD should work, not sure about WSDL though.
